import seaborn as sns
import matplotlib.pyplot as plt
df=sns.load_dataset("tips")
sns.set_style("whitegrid")
sns.set_context("notebook")
sns.set_palette("pastel")
plt.figure(figsize=(8, 5))
sns.barplot(x="day", y="total_bill", data=df)
plt.title("Average Total Bill by Day")
plt.xlabel("Day of the week")
plt.ylabel("Average total bill")
plt.tight_layout()
plt.show()
plt.figure(figsize=(8, 5))
sns.scatterplot(x="total_bill",y="tip",data=df)
plt.title("Relationship between Total Bill and Tip")
plt.xlabel("Total Bill amount")
plt.ylabel("Tip amount")
plt.tight_layout()
plt.show()