import numpy as np
student_id=np.arange(101,121)
print("Student ids",student_id)
print("Shape",student_id.shape)
print("Size",student_id.size)
print("Data Type",student_id.dtype)
print("="*40)
attendance=np.ones((5,5),dtype=int)
print("Weekly attendance",attendance)
print("Dimension",attendance.ndim)
print("="*40)
scores=np.zeros((4,3))
print("Scores:",scores)
print("="*40)
grading_scale = np.linspace(0, 100, 6)
print("\nGrading Scale:", grading_scale)
identity_matrix = np.eye(5)
diagonal_matrix = np.diag([2, 4, 6, 8, 10])
print("\nIdentity Matrix:\n", identity_matrix)
print("\nDiagonal Matrix:\n", diagonal_matrix)